#!/usr/bin/env node
// Generates environment.generated.ts (gitignored) from the
// COINGECKO_API_KEY environment variable, so the real key never lives in
// a committed file. Run automatically before `build`/`serve`/`test` via
// each target's `dependsOn` in project.json.
//
// Strict mode (default, used by build/serve): fails loudly if
// COINGECKO_API_KEY isn't set, instead of shipping a broken bundle.
// --optional mode (used by test): writes a harmless placeholder instead
// of failing, since tests never make a real network call with this value.
import { writeFileSync, readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join, resolve } from 'node:path';

// Same convention as coingecko.spec.ts's readCoinGeckoApiKeyFromEnvFile():
// secrets live in .env one level above the repo root, per AGENTS.md. Nx's
// `run-commands` executor defaults cwd to the workspace root, same as
// `nx test`, so this resolves the same way. On Vercel, process.env is
// already set directly by the platform and ../.env simply doesn't exist,
// so this fallback is a no-op there.
function readApiKeyFromDotEnvOutsideRepo() {
  const envPath = resolve(process.cwd(), '../.env');
  if (!existsSync(envPath)) return undefined;
  const match = readFileSync(envPath, 'utf8').match(/^COINGECKO_API_KEY=(.+)$/m);
  return match?.[1]?.trim();
}

const isOptional = process.argv.includes('--optional');
const apiKey = process.env.COINGECKO_API_KEY || readApiKeyFromDotEnvOutsideRepo();

if (!apiKey && !isOptional) {
  console.error(
    [
      '',
      '[generate-env] Missing required COINGECKO_API_KEY environment variable.',
      '',
      'Set it before building or serving portfolio-showcase:',
      '  - Local dev (bash/WSL): export COINGECKO_API_KEY=your-key',
      '  - Local dev (PowerShell): $env:COINGECKO_API_KEY = "your-key"',
      '  - Local dev (persistent): add COINGECKO_API_KEY=your-key to the',
      '    .env file one level above the repo root (see AGENTS.md)',
      '  - Vercel: Project Settings -> Environment Variables',
      '',
      'See README.md for details.',
      '',
    ].join('\n'),
  );
  process.exit(1);
}

const outputPath = join(
  dirname(fileURLToPath(import.meta.url)),
  '../src/environments/environment.generated.ts',
);

const value = apiKey ?? 'MISSING_COINGECKO_API_KEY';

writeFileSync(
  outputPath,
  [
    '// AUTO-GENERATED by scripts/generate-env.mjs from the COINGECKO_API_KEY',
    '// environment variable. Never commit a real key here or in',
    '// environment.ts / environment.production.ts (see .gitignore).',
    `export const COINGECKO_API_KEY = ${JSON.stringify(value)};`,
    '',
  ].join('\n'),
);

console.log(
  apiKey
    ? '[generate-env] Wrote environment.generated.ts with COINGECKO_API_KEY.'
    : '[generate-env] COINGECKO_API_KEY not set; wrote a placeholder (--optional mode, e.g. for tests).',
);
